chore(ci): remove toolchain check toolchain in go.mod before lint
Signed-off-by: Evgeniy Frolov <evgeniy.frolov@flant.com>

diff --git a/templates/lint.yml b/templates/lint.yml
--- a/templates/lint.yml
+++ b/templates/lint.yml
@@ -1,4 +1,9 @@
 .lint:
   stage: lint
   script:
+    - |
+      if grep -q '^[[:space:]]*toolchain' go.mod; then
+        echo "Error: go.mod must not contain a 'toolchain' directive"
+        exit 1
+      fi
     - task --yes -p lint
